# Generated by Django 5.0.7 on 2024-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.IntegerField(
                null=True, unique=True, verbose_name="Telegram Chat ID"
            ),
        ),
    ]
