# Generated by Django 5.0.7 on 2024-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
