# Generated by Django 5.0.7 on 2024-07-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
    ]
